# 语言
language: node_js
# 版本
node_js: lts/*
# 要最新的就行，所以克隆最近的一次commit
git:
  depth: 1
# 安装
install: yarn
# 指定了缓存的内容，这里是yarn安装的东西，既node_modules
cache: yarn
# build
script: yarn build
# build成功后开始部署，下面是travis-ci提供的一些比较便捷的写法，针对GitHub pages的
deploy:
  provider: pages
  # Make sure you have skip_cleanup set to true, otherwise Travis CI will delete all the files created during the build,
  # which will probably delete what you are trying to upload.
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  # 这里需要是true，否则会git push --force，把以前的记录覆盖了
  keep_history: true
  # 使用GitHub的用户名和邮箱
  committer_from_gh: true
  # 目标分支，我们的目标也是master
  target_branch: master
  # 指定分支，只有指定的分支提交时才会运行脚本
  on:
    branch: master
